""" added type attribute to pokemon

Revision ID: 5985359a08e6
Revises: 773425bbdbeb
Create Date: 2022-12-21 07:18:00.087570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5985359a08e6'
down_revision = '773425bbdbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
