""" made username uniqe in the table

Revision ID: 69602812a78d
Revises: ca12d889e9ad
Create Date: 2022-12-22 01:57:22.140169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69602812a78d'
down_revision = 'ca12d889e9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
