""" added date back to user

Revision ID: 773425bbdbeb
Revises: fda8b5ff93af
Create Date: 2022-12-21 01:23:03.866318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773425bbdbeb'
down_revision = 'fda8b5ff93af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
