""" erased date time for user

Revision ID: fda8b5ff93af
Revises: 52d0aa633b31
Create Date: 2022-12-21 01:10:47.210140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fda8b5ff93af'
down_revision = '52d0aa633b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.String(length=50), nullable=True))
        batch_op.drop_column('character')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###
